# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Robot mesh loading from mujoco_menagerie.

Downloads robot MJCF/URDF/mesh assets on first use, caches in ~/.cache/mujoco_menagerie/.
Each loader returns (meshes, ee_home_pose) where:
  - meshes: list of (name, trimesh.Trimesh, 4x4_transform)
  - ee_home_pose: (4, 4) float32 — EE pose at home configuration
"""

from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np
from scipy.spatial.transform import Rotation as R

from cosmos.utils import log
from cosmos.data.vfm.action.embodiment_c_spec import get_embodiment_c_urdf_path

_MENAGERIE_REPO = "https://github.com/google-deepmind/mujoco_menagerie"
_ROBOT_CACHE_DIR = Path("/tmp") / "mujoco_menagerie"
_AGIBOT_GEAR_LUSTRE_URDF_ROOT = Path(
    "/lustre/fsw/portfolios/cosmos/projects/cosmos_base_training/cosmos3_action_datasets/agibot_urdf/g1_urdf"
)
_AGIBOT_GEAR_LOCAL_SAMPLE_URDF_ROOT = Path(__file__).resolve().parents[6] / "dev/embodiment_c_samples/g1_urdf"
_FALLBACK_MESH_COLORS = np.asarray(
    [
        [52, 152, 219, 255],
        [243, 156, 18, 255],
        [155, 89, 182, 255],
        [46, 204, 113, 255],
        [231, 76, 60, 255],
        [26, 188, 156, 255],
        [241, 196, 15, 255],
        [52, 73, 94, 255],
        [127, 140, 141, 255],
        [211, 84, 0, 255],
        [39, 174, 96, 255],
        [41, 128, 185, 255],
    ],
    dtype=np.uint8,
)
_UNSPECIFIED_RGBA_VALUES = (
    np.asarray([0.5, 0.5, 0.5, 1.0], dtype=np.float32),
    np.asarray([1.0, 1.0, 1.0, 1.0], dtype=np.float32),
    # Some autogenerated URDF/MJCF assets use pink as a placeholder/default
    # material. Treat it as unspecified so meshes do not all render pink.
    np.asarray([1.0, 0.5, 1.0, 1.0], dtype=np.float32),
)
_UNSPECIFIED_MATERIAL_NAMES = {"", "default", "default_material"}


@dataclass(frozen=True)
class AgibotGeometry:
    """One AgiBot collision primitive attached to a URDF link."""

    name: str
    link_name: str
    mesh: Any
    local_transform: np.ndarray


def _fallback_mesh_color(name: str, index: int = 0) -> np.ndarray:
    """Return a stable fallback RGBA color for a mesh without material color."""

    key = name or f"mesh_{index}"
    palette_index = sum((char_idx + 1) * ord(char) for char_idx, char in enumerate(key))
    return _FALLBACK_MESH_COLORS[(palette_index + index) % len(_FALLBACK_MESH_COLORS)].copy()


def _is_unspecified_rgba(rgba: np.ndarray) -> bool:
    """Return whether RGBA is an uninformative default color."""

    return any(np.allclose(rgba, default_rgba, atol=1e-4) for default_rgba in _UNSPECIFIED_RGBA_VALUES)


def _apply_mesh_color(mesh: Any, rgba: np.ndarray) -> None:
    """Apply one RGBA color to all mesh faces for viser/trimesh rendering."""

    face_count = int(len(getattr(mesh, "faces", [])))
    if face_count > 0:
        mesh.visual.face_colors = np.tile(np.asarray(rgba, dtype=np.uint8), (face_count, 1))


# ── Robot-specific configuration ──────────────────────────────────────────────

# EE frame name candidates (tried in order by IK solver)
# ---------------------------------------------------------------------------
# End-effector frame references per dataset
# ---------------------------------------------------------------------------
# Each dataset records EE poses at a specific URDF link.  The IK solver must
# target the same frame (via ``ee_frame`` or the ``_EE_FRAME_CANDIDATES``
# fallback list).  Below we document, for every robot:
#   (a) which link the dataset records at, with upstream source reference,
#   (b) what that link physically represents (flange, gripper body, or TCP),
#   (c) any orientation transforms applied during recording.
#
# ── Google Robot (fractal / RT-1) ──────────────────────────────────────────
#   Recorded link: ``link_gripper_tcp``
#     The TFDS observation field is ``base_pose_tool_reached`` (shape (7,)).
#     Source: https://www.tensorflow.org/datasets/catalog/fractal20220817_data
#   Meaning: TCP — a calibrated tool-center-point 164 mm past the wrist
#     (``link_gripper``), roughly at the fingertip.  The name contains "tool"
#     and SimplerEnv's real→sim calibration targets the same link:
#       ``self.ee_link_name = "link_gripper_tcp"``
#     Source: https://github.com/simpler-env/ManiSkill2_real2sim/blob/ef7a4d4/mani_skill2_real2sim/agents/configs/google_robot/defaults.py#L141
#   Orientation: recorded as-is from the URDF FK (quaternion). No extra
#     rotation applied.
#   Re-referenced to: ``link_gripper`` (gripper body / last actuated link)
#     via ``_TCP_TO_FLANGE`` in the dataset class (−164 mm along local z).
#     See ``fractal.py`` for the full transform and rationale.
#   Our config: ``"ee_frame": "link_gripper"`` (explicit).
#   Important MJCF note: MuJoCo Menagerie places ``base_link`` at
#     ``pos="0 0 0.06205"`` under ``worldbody``. Pinocchio's
#     ``buildModelFromMJCF()`` omits this global root transform, so IK / dataset
#     poses live in a root-free world that is 62.05 mm lower than raw MuJoCo
#     body/site poses. We therefore strip the same root transform from MuJoCo
#     mesh/body/site outputs before rendering or comparing them.
#
# ── WidowX (bridge) ───────────────────────────────────────────────────────
#   Recorded link: ``ee_gripper_link``
#     The bridge data collection uses the Interbotix SDK's Modern Robotics FK
#     (``FKinSpace(M, Slist, q)``).  The M matrix for wx250s terminates at
#     ``ee_gripper_link`` — confirmed by the Interbotix source comment and
#     numerically: ``wx250s.M[0,3] = 0.458325`` matches ``ee_gripper_link``
#     position exactly (vs ``gripper_link`` at 0.3648).
#     Source: https://github.com/Interbotix/interbotix_ros_toolboxes/blob/main/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/mr_descriptions.py
#       Line 1: "Note that the end-effector is positioned at '<robot_name>/ee_gripper_link'"
#     SimplerEnv confirms: ``self.ee_link_name = "ee_gripper_link"``
#     Source: https://github.com/simpler-env/ManiSkill2_real2sim/blob/ef7a4d4/mani_skill2_real2sim/agents/configs/widowx/defaults.py#L87
#   Meaning: Interbotix-defined "end-effector" reference point, 93.6 mm past
#     the wrist (``gripper_link``), 27.6 mm past the finger pivot
#     (``fingers_link``).  This is roughly the grasp center between the
#     finger pads — *not* the fingertip.
#   Orientation: the bridge data collection applies ``DEFAULT_ROTATION`` to
#     the FK orientation before recording (in ``transform2state``):
#       ``euler = rotationMatrixToEulerAngles(rot.dot(default_rotation.T))``
#     where ``DEFAULT_ROTATION = [[0,0,1],[0,1,0],[-1,0,0]]``.
#     Source: https://github.com/rail-berkeley/bridge_data_robot/blob/main/widowx_envs/widowx_controller/src/widowx_controller/widowx_controller.py#L44
#   Re-referenced to: ``gripper_link`` (wrist rotate body / last actuated link)
#     via ``_TCP_TO_FLANGE`` in the dataset class (−93.6 mm along local x).
#     See ``bridge_orig_lerobot_dataset.py`` for the full transform and rationale.
#   Our config: ``"ee_frame": "gripper_link"`` (explicit).
#
# ── Franka + Robotiq 2F-85 (DROID) ────────────────────────────────────────
#   Recorded link: ``panda_link8`` (= Franka flange)
#     DROID's ``get_robot_state()`` calls Polymetis FK:
#       ``pos, quat = self._robot.robot_model.forward_kinematics(joint_positions)``
#     Source: https://github.com/droid-dataset/droid/blob/main/droid/franka/robot.py
#     Polymetis is configured with ``ee_link_name: panda_link8``:
#     Source: https://github.com/facebookresearch/fairo/blob/main/polymetis/polymetis/conf/robot_model/franka_panda.yaml
#   Meaning: flange — the bare mounting plate at the end of the Franka arm,
#     *before* the Robotiq gripper.
#   MJCF body: ``panda_hand`` in the composite model (pos 0 0 0.107
#     above ``link7``, identity quat).  This is at the panda_link8
#     (flange) position with link7 orientation, matching the URDF.
#     ``link7`` is panda_link7 (wrist), *not* the flange.
#   Orientation: Polymetis reports FK orientation at ``panda_link8`` frame
#     as-is. No extra rotation applied.
#   Current viewer convention: all Franka-backed datasets reuse this DROID
#     composite model, so ``franka_panda`` is the only supported Franka robot
#     config in this module.
#   Our config: ``"ee_frame": "panda_hand"`` (explicit).
# ---------------------------------------------------------------------------

_EE_FRAME_CANDIDATES = [
    "link_gripper_tcp",  # SimplerEnv Google Robot (calibrated TCP at fingertip)
    "link_gripper",  # Google Robot (Menagerie / fallback)
    "ee_gripper_link",  # SimplerEnv WidowX (end of finger chain)
    "gripper_link",  # WidowX (MuJoCo body name)
    "wx250s/gripper_link",  # WidowX Menagerie (prefixed body name)
    "gripper",  # Google Robot (Menagerie site)
    "hand",  # Franka Panda (standard gripper)
    "attachment",  # Franka + Robotiq
    "attachment_site",  # UR5e (mujoco_menagerie)
    "wx250s/gripper_link",  # WidowX 250S (Menagerie)
    "ee_link",  # generic
    "tool0",  # generic industrial
]

# Robot-specific configs: menagerie name, MJCF filename, joint info, finger range.
ROBOT_CONFIGS = {
    "google_robot": {
        "menagerie": "google_robot",
        "mjcf": "robot.xml",
        # EE: link_gripper (gripper body / last actuated link).
        # The Menagerie model has link_gripper directly (no TCP frame).
        # The dataset applies _TCP_TO_FLANGE to shift from the recorded
        # link_gripper_tcp to link_gripper, so poses already target this frame.
        # MuJoCo Menagerie also adds a global worldbody -> base_link offset
        # (+62.05 mm in z). Pinocchio's MJCF importer omits that root transform,
        # so the viewer removes it from MuJoCo outputs to keep meshes / body
        # frames aligned with dataset poses and IK outputs.
        "ee_frame": "link_gripper",
        "pinocchio_removed_root_body": "base_link",
        "arm_joints": [
            "joint_torso",
            "joint_shoulder",
            "joint_bicep",
            "joint_elbow",
            "joint_forearm",
            "joint_wrist",
            "joint_gripper",
        ],
        "n_arm_joints": 7,
        "finger_joint_names": ["joint_finger_left", "joint_finger_right"],
        "finger_min": 0.01,
        "finger_max": 1.30,
        "finger_close_is_max": True,
        "camera_body": None,
    },
    "franka_panda": {
        "menagerie": "droid_franka_robotiq",
        "mjcf": "panda_updated_robotiq_2f85.xml",
        # EE: panda_link8 (flange) — the bare mounting plate, *not* the
        # gripper TCP.  MJCF body: ``panda_hand`` in the composite model
        # (pos 0 0 0.107 above link7, identity quat).

        "ee_frame": "panda_hand",
        "arm_joints": [
            "joint1",
            "joint2",
            "joint3",
            "joint4",
            "joint5",
            "joint6",
            "joint7",
        ],
        "n_arm_joints": 7,
        "finger_min": 0.0,
        "finger_max": 0.8,
        "finger_close_is_max": True,
        # All Robotiq 2F-85 chain joints (some share names with bodies in
        # pinocchio MJCF parse — must keep all to avoid buildReducedModel error)
        "finger_joint_names": [
            "right_driver_joint",
            "left_driver_joint",
            "left_spring_link_joint",
            "left_follower",
            "right_spring_link_joint",
            "right_follower_joint",
        ],
        "camera_body": None,
    },
    "widowx": {
        "menagerie": "trossen_wx250s",
        "mjcf": "wx250s.xml",
        # EE: gripper_link (wrist rotate body / last actuated link).
        # The Menagerie model has gripper_link directly.
        # The dataset applies _TCP_TO_FLANGE to shift from the recorded
        # ee_gripper_link to gripper_link, so poses already target this frame.
        "ee_frame": "gripper_link",
        "arm_joints": [
            "waist",
            "shoulder",
            "elbow",
            "forearm_roll",
            "wrist_angle",
            "wrist_rotate",
        ],
        "n_arm_joints": 6,
        "finger_min": 0.015,
        "finger_max": 0.037,
        "finger_close_is_max": False,
        "finger_joint_names": ["left_finger", "right_finger"],
        "camera_body": None,
    },
    "ur5e": {
        "menagerie": "ur5e_robotiq",
        "mjcf": "ur5e_robotiq_2f85.xml",
        # EE: attachment_site — the UR5e flange site where the Robotiq mounts.
        # joint_configs[:, 6] raw UR gripper maps directly to Robotiq ctrl:
        # ctrl = raw * 255 (0=open, 255=closed).
        "ee_frame": "attachment_site",
        "n_arm_joints": 6,
        "finger_min": 0.0,
        "finger_max": 255.0,
        "finger_close_is_max": False,
        "camera_body": None,
    },
    "embodiment_c": {
        # No menagerie — uses local AgiBot G1/omnipicker URDF assets.
        # The dataset targets the gripper base/flange, not the TCP/center link.
        "menagerie": None,
        "ee_frame": "gripper_r_base_link",
        "arm_joints": [f"idx{11 + i:02d}_right_arm_joint{i}" for i in range(1, 8)],
        "n_arm_joints": 7,
        "finger_min": 0.0,
        "finger_max": 1.0,
        "finger_close_is_max": False,
        "camera_body": "head_pitch_link",
    },
}


def get_urdf_path(robot_name: str) -> str | None:
    """Get URDF path for a robot if available, else None (falls back to MJCF in caller)."""
    cfg = ROBOT_CONFIGS.get(robot_name)
    if cfg is None:
        return None

    if robot_name == "embodiment_c":
        return str(get_embodiment_c_urdf_path())

    menagerie_name = cfg.get("menagerie")
    if menagerie_name is None:
        return None
    mjcf_dir = _ensure_robot_assets(menagerie_name)

    urdf_filename = cfg.get("urdf")
    if urdf_filename:
        urdf_path = mjcf_dir / urdf_filename
        if urdf_path.exists():
            return str(urdf_path)

    urdfs = list(mjcf_dir.glob("*.urdf"))
    if urdfs:
        return str(urdfs[0])

    return None


def get_mjcf_path(robot_name: str) -> str:
    """Get MJCF path for a robot, downloading from mujoco_menagerie if needed."""
    cfg = ROBOT_CONFIGS.get(robot_name)
    if cfg is None:
        raise ValueError(f"Unknown robot: {robot_name}. Available: {list(ROBOT_CONFIGS.keys())}")

    menagerie_name = cfg.get("menagerie")
    if menagerie_name is None:
        raise FileNotFoundError(f"Robot {robot_name!r} does not have a MuJoCo MJCF asset.")
    mjcf_filename = cfg.get("mjcf", "robot.xml")

    mjcf_dir = _ensure_robot_assets(menagerie_name)
    mjcf_path = mjcf_dir / mjcf_filename
    if mjcf_path.exists():
        return str(mjcf_path)

    fallback = mjcf_dir / "robot.xml"
    if fallback.exists():
        return str(fallback)

    raise FileNotFoundError(f"MJCF not found: {mjcf_path} (also tried robot.xml)")


# ── Asset download ───────────────────────────────────────────────────────────


def _ensure_robot_assets(robot_name: str) -> Path:
    """Ensure robot MJCF and mesh assets are available locally.

    Downloads from mujoco_menagerie GitHub repo if not found.
    For composite robots (``droid_franka_robotiq``), downloads from both
    MuJoCo Menagerie and MuJoCo Playground and merges assets.

    Assets are cached in ~/.cache/mujoco_menagerie/<robot_name>/.

    Returns:
        Path to the cached MJCF directory (caller picks the right .xml).
    """
    cached_dir = _ROBOT_CACHE_DIR / robot_name
    if cached_dir.exists():
        return cached_dir

    # Composite: Franka arm + Robotiq 2F-85 gripper (DROID setup)
    if robot_name == "droid_franka_robotiq":
        return _build_droid_franka_robotiq()

    # Composite: UR5e arm + Robotiq 2F-85 gripper (RoboMIND UR setup)
    if robot_name == "ur5e_robotiq":
        return _build_ur5e_robotiq()

    log.info(f"Downloading {robot_name} assets from mujoco_menagerie...")
    _download_menagerie_model(robot_name)
    return cached_dir


def _download_menagerie_model(model_name: str) -> Path:
    """Download a single model from MuJoCo Menagerie. Returns cached path."""
    cached_dir = _ROBOT_CACHE_DIR / model_name
    if cached_dir.exists():
        return cached_dir

    import shutil
    import subprocess
    import tempfile

    _ROBOT_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        subprocess.run(
            ["git", "clone", "--depth=1", "--filter=blob:none", "--sparse", _MENAGERIE_REPO, tmpdir],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["git", "sparse-checkout", "set", model_name],
            cwd=tmpdir,
            check=True,
            capture_output=True,
        )
        src = Path(tmpdir) / model_name
        dst = _ROBOT_CACHE_DIR / model_name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)

    log.info(f"Cached {model_name} assets at {dst}")
    return dst


def _build_droid_franka_robotiq() -> Path:
    """Prepare composite Franka + Robotiq 2F-85 MJCF for DROID visualization.

    The hand-tuned composite XML is committed in the repo alongside this
    module (``droid_franka_robotiq_2f85.xml``).  This function downloads the
    mesh assets from MuJoCo Menagerie (``franka_emika_panda`` +
    ``robotiq_2f85_v4``) and copies them together with the XML into a cache
    directory that MuJoCo can load from.
    """
    import shutil

    log.info("Preparing composite Franka + Robotiq 2F-85 (committed XML + Menagerie assets)...")

    franka_dir = _download_menagerie_model("franka_emika_panda")
    robotiq_dir = _download_menagerie_model("robotiq_2f85_v4")

    dst = _ROBOT_CACHE_DIR / "droid_franka_robotiq"
    dst.mkdir(parents=True, exist_ok=True)
    assets_dir = dst / "assets"
    assets_dir.mkdir(exist_ok=True)

    for f in (franka_dir / "assets").iterdir():
        shutil.copy2(f, assets_dir / f.name)
    for f in (robotiq_dir / "assets").iterdir():
        shutil.copy2(f, assets_dir / f.name)

    committed_xml = Path(__file__).parent / "droid_franka_robotiq_2f85.xml"
    out_path = dst / "panda_updated_robotiq_2f85.xml"
    shutil.copy2(committed_xml, out_path)

    log.info(f"Prepared composite Franka + Robotiq 2F-85 at {dst}")
    return dst


def _build_ur5e_robotiq() -> Path:
    """Prepare composite UR5e + Robotiq 2F-85 MJCF for RoboMIND UR visualization.

    The hand-tuned composite XML is committed in the repo alongside this
    module (``ur5e_robotiq_2f85.xml``).  This function downloads the mesh
    assets from MuJoCo Menagerie (``universal_robots_ur5e`` +
    ``robotiq_2f85_v4``) and copies them together with the XML into a cache
    directory that MuJoCo can load from.
    """
    import shutil

    log.info("Preparing composite UR5e + Robotiq 2F-85 (committed XML + Menagerie assets)...")

    ur5e_dir = _download_menagerie_model("universal_robots_ur5e")
    robotiq_dir = _download_menagerie_model("robotiq_2f85_v4")

    dst = _ROBOT_CACHE_DIR / "ur5e_robotiq"
    dst.mkdir(parents=True, exist_ok=True)
    assets_dir = dst / "assets"
    assets_dir.mkdir(exist_ok=True)

    for f in (ur5e_dir / "assets").iterdir():
        shutil.copy2(f, assets_dir / f.name)
    for f in (robotiq_dir / "assets").iterdir():
        shutil.copy2(f, assets_dir / f.name)

    committed_xml = Path(__file__).parent / "ur5e_robotiq_2f85.xml"
    shutil.copy2(committed_xml, dst / "ur5e_robotiq_2f85.xml")

    log.info(f"Prepared composite UR5e + Robotiq 2F-85 at {dst}")
    return dst


# ── Robot loaders ────────────────────────────────────────────────────────────


def _load_google_robot() -> tuple[list, np.ndarray]:
    """Load Google Robot from MuJoCo Menagerie.

    Uses the official google_robot model from
    https://github.com/google-deepmind/mujoco_menagerie/tree/main/google_robot
    which has visual OBJ meshes for accurate rendering.
    """
    import mujoco

    cfg = ROBOT_CONFIGS["google_robot"]
    mjcf_dir = _ensure_robot_assets(cfg["menagerie"])
    mjcf_path = mjcf_dir / cfg["mjcf"]
    model = mujoco.MjModel.from_xml_path(str(mjcf_path))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)

    meshes = _extract_mujoco_meshes(model, data)
    world_correction = get_mujoco_to_pinocchio_world_transform(model, data, "google_robot")
    if not np.allclose(world_correction, np.eye(4, dtype=np.float32)):
        meshes = _apply_world_transform_to_meshes(meshes, world_correction)

    # Find EE pose at link_gripper
    ee_pose = np.eye(4, dtype=np.float32)
    for i in range(model.nbody):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) or ""
        if name == "link_gripper":
            ee_pose[:3, 3] = data.xpos[i].astype(np.float32)
            ee_pose[:3, :3] = data.xmat[i].reshape(3, 3).astype(np.float32)
            break
    ee_pose = (world_correction @ ee_pose).astype(np.float32)

    log.info(f"Google Robot (Menagerie) loaded: {len(meshes)} meshes, EE pos={ee_pose[:3, 3]}")
    return meshes, ee_pose


def _load_franka_panda() -> tuple[list, np.ndarray]:
    """Load Franka Panda + Robotiq 2F-85 gripper (DROID variant).

    Uses the composite model built from MuJoCo Menagerie
    (``franka_emika_panda`` arm + ``robotiq_2f85_v4`` gripper).
    """
    import mujoco

    mjcf_dir = _ensure_robot_assets("droid_franka_robotiq")
    mjcf_path = mjcf_dir / "panda_updated_robotiq_2f85.xml"
    model = mujoco.MjModel.from_xml_path(str(mjcf_path))
    data = mujoco.MjData(model)

    # Franka home configuration
    home_qpos = np.array([0.0, -0.78, 0.0, -2.36, 0.0, 1.57, 0.78])
    data.qpos[: len(home_qpos)] = home_qpos
    mujoco.mj_forward(model, data)

    meshes = _extract_mujoco_meshes(model, data)

    # EE pose: use the "gripper" site (on the Robotiq base), or fall
    # back to "base_mount" / "attachment" body if site isn't found.
    ee_pose = np.eye(4, dtype=np.float32)
    for si in range(model.nsite):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_SITE, si) or ""
        if name == "gripper":
            ee_pose[:3, 3] = data.site_xpos[si].astype(np.float32)
            ee_pose[:3, :3] = data.site_xmat[si].reshape(3, 3).astype(np.float32)
            break
    else:
        # Fallback to body search
        for i in range(model.nbody):
            name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) or ""
            if name in ("base_mount", "attachment"):
                ee_pose[:3, 3] = data.xpos[i].astype(np.float32)
                ee_pose[:3, :3] = data.xmat[i].reshape(3, 3).astype(np.float32)
                break

    log.info(f"Franka Panda + Robotiq loaded: {len(meshes)} meshes, EE pos={ee_pose[:3, 3]}")
    return meshes, ee_pose


def _load_widowx() -> tuple[list, np.ndarray]:
    """Load WidowX 250S from MuJoCo Menagerie (trossen_wx250s).

    Uses the official Trossen Robotics WX250S model from
    https://github.com/google-deepmind/mujoco_menagerie/tree/main/trossen_wx250s
    which has visual OBJ meshes for accurate rendering.
    """
    import mujoco

    cfg = ROBOT_CONFIGS["widowx"]
    mjcf_dir = _ensure_robot_assets(cfg["menagerie"])
    mjcf_path = mjcf_dir / cfg["mjcf"]
    model = mujoco.MjModel.from_xml_path(str(mjcf_path))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)

    meshes = _extract_mujoco_meshes(model, data)

    ee_pose = np.eye(4, dtype=np.float32)
    for i in range(model.nbody):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) or ""
        if name == "gripper_link":
            ee_pose[:3, 3] = data.xpos[i].astype(np.float32)
            ee_pose[:3, :3] = data.xmat[i].reshape(3, 3).astype(np.float32)
            break

    log.info(f"WidowX 250S (Menagerie) loaded: {len(meshes)} meshes, EE pos={ee_pose[:3, 3]}")
    return meshes, ee_pose


def _load_ur5e() -> tuple[list, np.ndarray]:
    """Load UR5e + Robotiq 2F-85 composite from MuJoCo Menagerie."""
    import mujoco

    mjcf_dir = _ensure_robot_assets("ur5e_robotiq")
    mjcf_path = mjcf_dir / "ur5e_robotiq_2f85.xml"
    model = mujoco.MjModel.from_xml_path(str(mjcf_path))
    data = mujoco.MjData(model)

    # UR5e home: -90, -90, 90, -90, -90, 0 (degrees → radians); gripper open
    home_qpos = np.array([-1.5708, -1.5708, 1.5708, -1.5708, -1.5708, 0.0])
    data.qpos[: len(home_qpos)] = home_qpos
    mujoco.mj_forward(model, data)

    meshes = _extract_mujoco_meshes(model, data)

    # EE pose: use robotiq_base body (the flange-to-gripper attachment point)
    ee_pose = np.eye(4, dtype=np.float32)
    for i in range(model.nbody):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) or ""
        if name == "robotiq_base":
            ee_pose[:3, 3] = data.xpos[i].astype(np.float32)
            ee_pose[:3, :3] = data.xmat[i].reshape(3, 3).astype(np.float32)
            break

    log.info(f"UR5e+Robotiq loaded: {len(meshes)} meshes, EE pos={ee_pose[:3, 3]}")
    return meshes, ee_pose


def _load_embodiment_c() -> tuple[list, np.ndarray]:
    """Load Embodiment C G1/omnipicker robot meshes from the local URDF."""

    from cosmos.data.vfm.action.embodiment_c_fk import compute_link_poses_batch

    poses_batch = compute_link_poses_batch(np.zeros((1, 32), dtype=np.float32), "embodiment_c_gripper")
    poses = {link_name: link_poses[0] for link_name, link_poses in poses_batch.items()}
    geometries = get_embodiment_c_collision_geometries()
    meshes = []
    for geometry in geometries:
        link_pose = poses.get(geometry.link_name)
        if link_pose is None:
            continue
        world_transform = link_pose @ geometry.local_transform
        meshes.append((geometry.name, geometry.mesh.copy(), world_transform.astype(np.float32)))

    ee_pose = poses.get("gripper_r_base_link", np.eye(4, dtype=np.float32)).astype(np.float32)
    log.info(f"Embodiment C (G1 omnipicker geometry) loaded: {len(meshes)} meshes, EE pos={ee_pose[:3, 3]}")
    return meshes, ee_pose


def _parse_urdf_origin(origin_element) -> np.ndarray:
    transform = np.eye(4, dtype=np.float32)
    if origin_element is None:
        return transform

    xyz_text = origin_element.attrib.get("xyz", "0 0 0")
    rpy_text = origin_element.attrib.get("rpy", "0 0 0")
    xyz = np.asarray([float(value) for value in xyz_text.split()], dtype=np.float32)
    rpy = np.asarray([float(value) for value in rpy_text.split()], dtype=np.float32)
    transform[:3, :3] = R.from_euler("xyz", rpy).as_matrix().astype(np.float32)
    transform[:3, 3] = xyz
    return transform


def _parse_urdf_color(color_element: ET.Element | None) -> np.ndarray | None:
    if color_element is None:
        return None
    rgba_text = color_element.attrib.get("rgba")
    if not rgba_text:
        return None
    rgba = np.asarray([float(value) for value in rgba_text.split()], dtype=np.float32)
    if rgba.shape != (4,):
        return None
    return (np.clip(rgba, 0.0, 1.0) * 255.0).astype(np.uint8)


def _parse_urdf_material_colors(root: ET.Element) -> dict[str, np.ndarray]:
    material_colors: dict[str, np.ndarray] = {}
    for material_element in root.findall("material"):
        material_name = material_element.attrib.get("name", "")
        color = _parse_urdf_color(material_element.find("color"))
        if material_name and color is not None:
            material_colors[material_name] = color
    return material_colors


def _resolve_urdf_visual_color(parent_element: ET.Element, material_colors: dict[str, np.ndarray]) -> np.ndarray | None:
    material_element = parent_element.find("material")
    if material_element is None:
        return None

    material_name = material_element.attrib.get("name", "")
    color = _parse_urdf_color(material_element.find("color"))
    if color is None and material_name:
        color = material_colors.get(material_name)
    if color is None:
        return None

    color_unit = color.astype(np.float32) / 255.0
    if material_name.lower() in _UNSPECIFIED_MATERIAL_NAMES or _is_unspecified_rgba(color_unit):
        return None
    return color


def _agibot_urdf_asset_roots() -> list[Path]:
    """Return candidate roots that can satisfy package://genie_robot_description assets."""

    roots: list[Path] = []
    env_urdf_root = os.environ.get("AGIBOT_GEAR_URDF_ROOT")
    if env_urdf_root:
        roots.append(Path(env_urdf_root))
    env_mesh_root = os.environ.get("AGIBOT_GEAR_MESH_ROOT")
    if env_mesh_root:
        roots.append(Path(env_mesh_root))
    roots.extend(
        [
            get_embodiment_c_urdf_path().parent,
            _AGIBOT_GEAR_LUSTRE_URDF_ROOT,
            _AGIBOT_GEAR_LOCAL_SAMPLE_URDF_ROOT,
        ]
    )

    unique_roots: list[Path] = []
    seen: set[Path] = set()
    for root in roots:
        resolved = root.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        unique_roots.append(resolved)
    return unique_roots


def _resolve_agibot_mesh_path(filename: str) -> Path:
    if filename.startswith("package://genie_robot_description/"):
        rel = filename.removeprefix("package://genie_robot_description/")
        candidates: list[Path] = []
        for root in _agibot_urdf_asset_roots():
            candidates.append(root / rel)
            if rel.startswith("meshes/"):
                candidates.append(root / rel.removeprefix("meshes/"))
        for candidate in candidates:
            if candidate.is_file():
                return candidate
        return candidates[0]
    path = Path(filename)
    if path.is_absolute():
        return path
    return get_embodiment_c_urdf_path().parent / path


def _build_urdf_geometry_mesh(geometry_element: ET.Element | None, warn_missing_mesh: bool = False) -> Any | None:
    import trimesh

    if geometry_element is None:
        return None

    mesh_element = geometry_element.find("mesh")
    if mesh_element is not None:
        filename = mesh_element.attrib.get("filename")
        if not filename:
            return None
        mesh_path = _resolve_agibot_mesh_path(filename)
        if not mesh_path.is_file():
            if warn_missing_mesh:
                log.warning(f"AgiBot mesh file missing: {mesh_path}")
            return None
        try:
            mesh = trimesh.load(mesh_path, force="mesh")
            if hasattr(mesh, "geometry"):
                mesh = trimesh.util.concatenate(tuple(mesh.geometry.values()))
        except Exception as exc:
            log.warning(f"Failed to load AgiBot mesh {mesh_path}: {exc}")
            return None
        scale_text = mesh_element.attrib.get("scale")
        if scale_text:
            mesh.apply_scale([float(value) for value in scale_text.split()])
        return mesh

    box = geometry_element.find("box")
    if box is not None:
        size = np.asarray([float(value) for value in box.attrib["size"].split()], dtype=np.float32)
        return trimesh.creation.box(extents=size)

    sphere = geometry_element.find("sphere")
    if sphere is not None:
        radius = float(sphere.attrib["radius"])
        return trimesh.creation.icosphere(radius=radius)

    cylinder = geometry_element.find("cylinder")
    if cylinder is not None:
        radius = float(cylinder.attrib["radius"])
        length = float(cylinder.attrib["length"])
        return trimesh.creation.cylinder(radius=radius, height=length)

    return None


@lru_cache(maxsize=1)
def _load_embodiment_c_collision_geometries() -> tuple[AgibotGeometry, ...]:
    root = ET.parse(get_embodiment_c_urdf_path()).getroot()
    material_colors = _parse_urdf_material_colors(root)
    geometries: list[AgibotGeometry] = []

    for link_element in root.findall("link"):
        link_name = link_element.attrib["name"]
        visual_elements = link_element.findall("visual")
        collision_elements = link_element.findall("collision")
        # Prefer visual meshes when the real asset files are available. Collision
        # primitives remain the fallback for environments without AgiBot mesh assets.
        for elements, warn_missing_meshes in ((visual_elements, False), (collision_elements, False)):
            loaded_before = len(geometries)
            for geometry_idx, parent_element in enumerate(elements):
                geometry_element = parent_element.find("geometry")
                mesh = _build_urdf_geometry_mesh(geometry_element, warn_missing_mesh=warn_missing_meshes)
                if mesh is None:
                    continue
                geometry_name = f"{link_name}_geometry_{geometry_idx}"
                face_color = _resolve_urdf_visual_color(parent_element, material_colors)
                if face_color is None:
                    face_color = _fallback_mesh_color(geometry_name, geometry_idx)
                _apply_mesh_color(mesh, face_color)
                local_transform = _parse_urdf_origin(parent_element.find("origin"))
                geometries.append(
                    AgibotGeometry(
                        name=geometry_name,
                        link_name=link_name,
                        mesh=mesh,
                        local_transform=local_transform,
                    )
                )
            if len(geometries) > loaded_before:
                break

    return tuple(geometries)


def get_embodiment_c_collision_geometries() -> list[AgibotGeometry]:
    """Return cached AgiBot primitive collision geometries from the committed G1 URDF."""

    return list(_load_embodiment_c_collision_geometries())


# ── Helpers ──────────────────────────────────────────────────────────────────


def _get_visual_geom_ids(model) -> list[int]:
    """Get visual geom IDs from a MuJoCo model.

    Strategy:
    1. Google Robot uses *_v suffix for visual meshes → use those
    2. Other robots (Franka, WidowX) use geom_group=2 for visual → use those
    3. Fallback: all mesh geoms

    Includes both mesh geoms and primitive geoms (box, cylinder, sphere) in group 2.
    """
    import mujoco

    VISUAL_TYPES = {
        mujoco.mjtGeom.mjGEOM_MESH,
        mujoco.mjtGeom.mjGEOM_BOX,
        mujoco.mjtGeom.mjGEOM_CYLINDER,
        mujoco.mjtGeom.mjGEOM_SPHERE,
        mujoco.mjtGeom.mjGEOM_CAPSULE,
        mujoco.mjtGeom.mjGEOM_ELLIPSOID,
    }

    v_ids = []
    group2_ids = []
    all_ids = []
    for gi in range(model.ngeom):
        gtype = model.geom_type[gi]
        if gtype not in VISUAL_TYPES:
            continue
        all_ids.append(gi)
        if gtype == mujoco.mjtGeom.mjGEOM_MESH:
            mesh_id = model.geom_dataid[gi]
            mesh_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_MESH, mesh_id) or ""
            if mesh_name.endswith("_v"):
                v_ids.append(gi)
        if model.geom_group[gi] == 2:
            group2_ids.append(gi)

    # Priority: _v suffix > group 2 > all
    if v_ids:
        return v_ids
    if group2_ids:
        return group2_ids
    return all_ids


def _resolve_geom_color(model, gi: int, geom_name: str) -> np.ndarray:
    """Resolve the effective RGBA color for a MuJoCo geom.

    Priority:
    1. If geom has a material with a diffuse texture → sample average texture color
    2. If geom has a material with non-default rgba → use mat_rgba
    3. If geom_rgba is non-default → use geom_rgba
    4. Fallback: deterministic per-geom color

    Returns (4,) uint8 RGBA.
    """

    rgba = model.geom_rgba[gi].copy()  # (4,) float [0,1]
    mat_id = model.geom_matid[gi]

    if mat_id >= 0:
        # Check if material has a diffuse texture
        tex_id = model.mat_texid[mat_id][1]  # index 1 = diffuse texture
        if tex_id >= 0:
            # Sample average color from the texture
            tex_adr = model.tex_adr[tex_id]
            tex_w = model.tex_width[tex_id]
            tex_h = model.tex_height[tex_id]
            n_pixels = tex_w * tex_h
            tex_data = model.tex_data[tex_adr : tex_adr + n_pixels * 3].reshape(n_pixels, 3)
            avg_rgb = tex_data.mean(axis=0) / 255.0
            # Multiply by mat_rgba (which acts as a tint)
            mat_rgba = model.mat_rgba[mat_id]
            final = np.array(
                [
                    avg_rgb[0] * mat_rgba[0],
                    avg_rgb[1] * mat_rgba[1],
                    avg_rgb[2] * mat_rgba[2],
                    mat_rgba[3],
                ]
            )
            return (np.clip(final, 0, 1) * 255).astype(np.uint8)

        # No texture — use material rgba if it is informative.
        mat_rgba = model.mat_rgba[mat_id].copy()
        if not _is_unspecified_rgba(mat_rgba):
            return (np.clip(mat_rgba, 0, 1) * 255).astype(np.uint8)

    if not _is_unspecified_rgba(rgba):
        return (np.clip(rgba, 0, 1) * 255).astype(np.uint8)

    return _fallback_mesh_color(geom_name, gi)


def _extract_mujoco_meshes(model, data) -> list:
    """Extract visual geom meshes from a MuJoCo model as trimesh objects.

    Uses the same visual geom filtering as ``ik_solver._get_visual_geom_ids``
    to ensure mesh ordering matches IK transform output.

    For geoms with primitive types (box, cylinder, etc.), generates the
    corresponding trimesh primitive.

    Applies per-geom RGBA color from MuJoCo materials when available.

    Returns list of (geom_name, trimesh.Trimesh, 4x4_transform).
    """
    import mujoco
    import trimesh

    # Use the same visual filter as IK solver
    visual_geom_ids = _get_visual_geom_ids(model)

    meshes = []
    for gi in visual_geom_ids:
        gtype = model.geom_type[gi]
        pos = data.geom_xpos[gi].copy()
        rot = data.geom_xmat[gi].reshape(3, 3).copy()

        geom_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, gi) or f"geom_{gi}"
        face_color = _resolve_geom_color(model, gi, geom_name)

        mesh = None
        if gtype == mujoco.mjtGeom.mjGEOM_MESH:
            mesh_id = model.geom_dataid[gi]
            vert_start = model.mesh_vertadr[mesh_id]
            vert_count = model.mesh_vertnum[mesh_id]
            face_start = model.mesh_faceadr[mesh_id]
            face_count = model.mesh_facenum[mesh_id]
            verts = model.mesh_vert[vert_start : vert_start + vert_count].copy()
            faces = model.mesh_face[face_start : face_start + face_count].copy()
            mesh = trimesh.Trimesh(vertices=verts, faces=faces)
            _apply_mesh_color(mesh, face_color)
        elif gtype == mujoco.mjtGeom.mjGEOM_BOX:
            size = model.geom_size[gi].copy()
            mesh = trimesh.creation.box(extents=size * 2)
            _apply_mesh_color(mesh, face_color)
        elif gtype == mujoco.mjtGeom.mjGEOM_SPHERE:
            mesh = trimesh.creation.icosphere(radius=model.geom_size[gi][0])
            _apply_mesh_color(mesh, face_color)
        elif gtype == mujoco.mjtGeom.mjGEOM_CYLINDER:
            mesh = trimesh.creation.cylinder(radius=model.geom_size[gi][0], height=model.geom_size[gi][1] * 2)
            _apply_mesh_color(mesh, face_color)
        elif gtype == mujoco.mjtGeom.mjGEOM_CAPSULE:
            mesh = trimesh.creation.capsule(radius=model.geom_size[gi][0], height=model.geom_size[gi][1] * 2)
            _apply_mesh_color(mesh, face_color)

        if mesh is not None:
            transform = np.eye(4)
            transform[:3, :3] = rot
            transform[:3, 3] = pos
            meshes.append((geom_name, mesh, transform))
    return meshes


def get_mujoco_to_pinocchio_world_transform(model, data, robot_name: str | None = None) -> np.ndarray:
    """Return a correction that maps MuJoCo world poses into Pinocchio world.

    For some MJCFs, MuJoCo includes a fixed worldbody -> root-body transform
    that Pinocchio's ``buildModelFromMJCF()`` omits. When that happens, the IK
    solver and dataset poses live in a root-free world, while raw MuJoCo
    body/site poses are globally shifted. This helper returns the inverse root
    transform so callers can strip that offset from MuJoCo-derived meshes,
    body frames, and sites before comparing them against Pinocchio / dataset
    poses.
    """
    import mujoco

    cfg = ROBOT_CONFIGS.get(robot_name, {}) if robot_name else {}
    root_body_name = cfg.get("pinocchio_removed_root_body")
    if not root_body_name:
        return np.eye(4, dtype=np.float32)

    root_body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, root_body_name)
    if root_body_id < 0:
        log.warning(f"Configured root body '{root_body_name}' not found in MuJoCo model")
        return np.eye(4, dtype=np.float32)

    root_pose = np.eye(4, dtype=np.float32)
    root_pose[:3, 3] = data.xpos[root_body_id].astype(np.float32)
    root_pose[:3, :3] = data.xmat[root_body_id].reshape(3, 3).astype(np.float32)
    return np.linalg.inv(root_pose).astype(np.float32)


def _apply_world_transform_to_meshes(
    meshes: list[tuple[str, object, np.ndarray]],
    world_transform: np.ndarray,
) -> list[tuple[str, object, np.ndarray]]:
    """Left-multiply a world-space transform into each mesh pose."""
    transformed_meshes = []
    for name, mesh, transform in meshes:
        transformed_meshes.append((name, mesh, (world_transform @ transform).astype(np.float32)))
    return transformed_meshes


# ── Public API ───────────────────────────────────────────────────────────────


def get_robot_loaders() -> dict[str, callable]:
    """Get the robot loader registry.

    Maps robot_name → loader function that returns (meshes, ee_home_pose).
    """
    return {
        "google_robot": _load_google_robot,
        "franka_panda": _load_franka_panda,
        "widowx": _load_widowx,
        "ur5e": _load_ur5e,
        "embodiment_c": _load_embodiment_c,
    }


def extract_gripper_openings(unified_57d: np.ndarray, robot_name: str = "google_robot") -> np.ndarray:
    """Extract gripper opening fractions from unified action grasp state.

    Uses fingertip spread (f0-f1 distance) to invert the FK and recover
    the scalar gripper opening at each timestep.

    Args:
        unified_57d: (T, 57) unified action.
        robot_name: Robot identifier for FK lookup table.

    Returns:
        (T+1,) array of gripper openings in [0, 1].
    """
    T = unified_57d.shape[0]
    grasp = unified_57d[:, 18:33].reshape(T, 5, 3)
    all_grasp = np.concatenate([grasp[0:1], grasp], axis=0)

    # Build monotonic inverse lookup from FK (robot-specific)
    _gs = np.linspace(0, 1, 10001).astype(np.float32)
    try:
        if robot_name == "franka_panda":
            from cosmos.data.vfm.action.robot_descriptions.franka import franka_fingertip_fk

            _tips = franka_fingertip_fk(_gs)
        elif robot_name == "widowx":
            from cosmos.data.vfm.action.robot_descriptions.widowx import widowx_fingertip_fk

            _tips = widowx_fingertip_fk(_gs)
        elif robot_name == "ur5e":
            from cosmos.data.vfm.action.robot_descriptions.umi import _WSG50_MAX_WIDTH, umi_fingertip_fk

            _tips = umi_fingertip_fk(_gs * _WSG50_MAX_WIDTH)
        else:
            from cosmos.data.vfm.action.robot_descriptions.google_robot import (
                google_robot_fingertip_fk_vectorized,
            )

            _tips = google_robot_fingertip_fk_vectorized(_gs)
        _spreads = np.linalg.norm(_tips[:, 0] - _tips[:, 1], axis=1)
    except ImportError:
        # Fallback: linear approximation
        _spreads = _gs * 0.145
    _min_idx = int(np.argmin(_spreads))
    mono_gs = _gs[_min_idx:]
    mono_spreads = _spreads[_min_idx:]

    openings = np.zeros(T + 1, dtype=np.float32)
    for t in range(T + 1):
        f0, f1 = all_grasp[t, 0], all_grasp[t, 1]
        spread = np.linalg.norm(f0 - f1)
        if spread <= mono_spreads[0]:
            openings[t] = 0.0
        elif spread >= mono_spreads[-1]:
            openings[t] = 1.0
        else:
            openings[t] = float(np.interp(spread, mono_spreads, mono_gs))
    return openings
